# Generated by Django 3.0.5 on 2022-07-12 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price15',
            new_name='price10',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price16',
            new_name='price5',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price17',
            new_name='price6',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price18',
            new_name='price7',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price19',
            new_name='price8',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price20',
            new_name='price9',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product15',
            new_name='product10',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product16',
            new_name='product5',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product17',
            new_name='product6',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product18',
            new_name='product7',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product19',
            new_name='product8',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product20',
            new_name='product9',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price21',
            new_name='qty10',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price22',
            new_name='qty5',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price23',
            new_name='qty6',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price24',
            new_name='qty7',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price25',
            new_name='qty8',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price26',
            new_name='qty9',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product21',
            new_name='sku10',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product22',
            new_name='sku5',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product23',
            new_name='sku6',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product24',
            new_name='sku7',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product25',
            new_name='sku8',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='product26',
            new_name='sku9',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price27',
            new_name='total10',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price28',
            new_name='total5',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price29',
            new_name='total6',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='price30',
            new_name='total7',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='qty15',
            new_name='total8',
        ),
        migrations.RenameField(
            model_name='rawmaterials1',
            old_name='qty16',
            new_name='total9',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='product27',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='product28',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='product29',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='product30',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty17',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty18',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty19',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty20',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty21',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty22',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty23',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty24',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty25',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty26',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty27',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty28',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty29',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='qty30',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku15',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku16',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku17',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku18',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku19',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku20',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku21',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku22',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku23',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku24',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku25',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku26',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku27',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku28',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku29',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='sku30',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total15',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total16',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total17',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total18',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total19',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total20',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total21',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total22',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total23',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total24',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total25',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total26',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total27',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total28',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total29',
        ),
        migrations.RemoveField(
            model_name='rawmaterials1',
            name='total30',
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='price1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='price2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='price3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='price4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='product1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='product2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='product3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='product4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='qty1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='qty2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='qty3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='qty4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='sku1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='sku2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='sku3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='sku4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='total1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='total2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='total3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='total4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='rawmaterials3',
            fields=[
                ('rawmaterialsid', models.AutoField(primary_key=True, serialize=False, verbose_name='RAWMATERIALSID')),
                ('Type', models.CharField(blank=True, default='', max_length=255)),
                ('product16', models.CharField(blank=True, default='', max_length=255)),
                ('sku16', models.CharField(blank=True, default='', max_length=255)),
                ('qty16', models.IntegerField()),
                ('price16', models.IntegerField()),
                ('total16', models.IntegerField()),
                ('product17', models.CharField(blank=True, default='', max_length=255)),
                ('sku17', models.CharField(blank=True, default='', max_length=255)),
                ('qty17', models.IntegerField()),
                ('price17', models.IntegerField()),
                ('total17', models.IntegerField()),
                ('product18', models.CharField(blank=True, default='', max_length=255)),
                ('sku18', models.CharField(blank=True, default='', max_length=255)),
                ('qty18', models.IntegerField()),
                ('price18', models.IntegerField()),
                ('total18', models.IntegerField()),
                ('product19', models.CharField(blank=True, default='', max_length=255)),
                ('sku19', models.CharField(blank=True, default='', max_length=255)),
                ('qty19', models.IntegerField()),
                ('price19', models.IntegerField()),
                ('total19', models.IntegerField()),
                ('product20', models.CharField(blank=True, default='', max_length=255)),
                ('sku20', models.CharField(blank=True, default='', max_length=255)),
                ('qty20', models.IntegerField()),
                ('price20', models.IntegerField()),
                ('total20', models.IntegerField()),
                ('totalquantity3', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal3', models.CharField(blank=True, default='', max_length=255)),
                ('costofcomponents3', models.CharField(blank=True, default='', max_length=255)),
                ('typeofaddnlcost3', models.CharField(blank=True, default='', max_length=255)),
                ('percentage3', models.CharField(blank=True, default='', max_length=255)),
                ('amount3', models.CharField(blank=True, default='', max_length=255)),
                ('totaladdnlcost3', models.CharField(blank=True, default='', max_length=255)),
                ('effectivecost3', models.CharField(blank=True, default='', max_length=255)),
                ('effectiverate3', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('productionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.production')),
            ],
        ),
        migrations.CreateModel(
            name='rawmaterials2',
            fields=[
                ('rawmaterialsid', models.AutoField(primary_key=True, serialize=False, verbose_name='RAWMATERIALSID')),
                ('Type', models.CharField(blank=True, default='', max_length=255)),
                ('product11', models.CharField(blank=True, default='', max_length=255)),
                ('sku11', models.CharField(blank=True, default='', max_length=255)),
                ('qty11', models.IntegerField()),
                ('price11', models.IntegerField()),
                ('total11', models.IntegerField()),
                ('product12', models.CharField(blank=True, default='', max_length=255)),
                ('sku12', models.CharField(blank=True, default='', max_length=255)),
                ('qty12', models.IntegerField()),
                ('price12', models.IntegerField()),
                ('total12', models.IntegerField()),
                ('product13', models.CharField(blank=True, default='', max_length=255)),
                ('sku13', models.CharField(blank=True, default='', max_length=255)),
                ('qty13', models.IntegerField()),
                ('price13', models.IntegerField()),
                ('total13', models.IntegerField()),
                ('product14', models.CharField(blank=True, default='', max_length=255)),
                ('sku14', models.CharField(blank=True, default='', max_length=255)),
                ('qty14', models.IntegerField()),
                ('price14', models.IntegerField()),
                ('total14', models.IntegerField()),
                ('product15', models.CharField(blank=True, default='', max_length=255)),
                ('sku15', models.CharField(blank=True, default='', max_length=255)),
                ('qty15', models.IntegerField()),
                ('price15', models.IntegerField()),
                ('total15', models.IntegerField()),
                ('totalquantity2', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal2', models.CharField(blank=True, default='', max_length=255)),
                ('costofcomponents2', models.CharField(blank=True, default='', max_length=255)),
                ('typeofaddnlcost2', models.CharField(blank=True, default='', max_length=255)),
                ('percentage2', models.CharField(blank=True, default='', max_length=255)),
                ('amount2', models.CharField(blank=True, default='', max_length=255)),
                ('totaladdnlcost2', models.CharField(blank=True, default='', max_length=255)),
                ('effectivecost2', models.CharField(blank=True, default='', max_length=255)),
                ('effectiverate2', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('productionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.production')),
            ],
        ),
    ]
