# Generated by Django 4.0.1 on 2022-06-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, default='', max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('hsn', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturing_date', models.CharField(blank=True, default='', max_length=255)),
                ('expiry_date', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
