# Generated by Django 3.0.5 on 2022-07-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rawmaterials1_rawmaterials2_rawmaterials3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rawmaterials',
        ),
    ]
