# Generated by Django 3.0.5 on 2022-06-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220610_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='price',
        ),
        migrations.CreateModel(
            name='pricetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.production')),
            ],
        ),
    ]
