# Generated by Django 3.0.5 on 2022-07-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_rawmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='rawmaterials',
            fields=[
                ('rawmaterialsid', models.AutoField(primary_key=True, serialize=False, verbose_name='RAWMATERIALSID')),
                ('Type', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.CharField(blank=True, default='', max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.CharField(blank=True, default='', max_length=255)),
                ('product1', models.CharField(default='', max_length=255)),
                ('sku1', models.CharField(default='', max_length=255)),
                ('qty1', models.CharField(default='', max_length=255)),
                ('price1', models.CharField(default='', max_length=255)),
                ('total1', models.CharField(default='', max_length=255)),
                ('product2', models.CharField(blank=True, default='', max_length=255)),
                ('sku2', models.CharField(blank=True, default='', max_length=255)),
                ('qty2', models.CharField(blank=True, default='', max_length=255)),
                ('price2', models.CharField(blank=True, default='', max_length=255)),
                ('total2', models.CharField(blank=True, default='', max_length=255)),
                ('product3', models.CharField(blank=True, default='', max_length=255)),
                ('sku3', models.CharField(blank=True, default='', max_length=255)),
                ('qty3', models.CharField(blank=True, default='', max_length=255)),
                ('price3', models.CharField(blank=True, default='', max_length=255)),
                ('total3', models.CharField(blank=True, default='', max_length=255)),
                ('product4', models.CharField(blank=True, default='', max_length=255)),
                ('sku4', models.CharField(blank=True, default='', max_length=255)),
                ('qty4', models.CharField(blank=True, default='', max_length=255)),
                ('price4', models.CharField(blank=True, default='', max_length=255)),
                ('total4', models.CharField(blank=True, default='', max_length=255)),
                ('totalquantity', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal', models.CharField(blank=True, default='', max_length=255)),
                ('costofcomponents', models.CharField(blank=True, default='', max_length=255)),
                ('typeofaddnlcost', models.CharField(blank=True, default='', max_length=255)),
                ('percentage', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.CharField(blank=True, default='', max_length=255)),
                ('totaladdnlcost', models.CharField(blank=True, default='', max_length=255)),
                ('effectivecost', models.CharField(blank=True, default='', max_length=255)),
                ('effectiverate', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('productionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.production')),
            ],
        ),
    ]
