# Generated by Django 3.0.5 on 2022-06-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220616_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetable',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='pricetable',
            name='sku',
        ),
        migrations.AddField(
            model_name='pricetable',
            name='productdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.production'),
        ),
    ]
