# Generated by Django 3.0.5 on 2022-06-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220617_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetable',
            name='productdetails',
        ),
        migrations.AddField(
            model_name='pricetable',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.inventory')),
                ('noninventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.noninventory')),
            ],
        ),
    ]
