# Generated by Django 3.0.5 on 2022-06-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20220620_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
